# Generated by Django 5.2.1 on 2025-05-30 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('slug_kat', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('hari', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=2)),
                ('slug_ak', models.SlugField(blank=True, editable=False)),
                ('pupdate', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktivitas.kategori')),
            ],
        ),
    ]
