# Generated by Django 5.2.1 on 2025-05-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Youtube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("isi", models.TextField()),
                ("rating", models.CharField(max_length=10)),
                ("slug_art", models.SlugField(blank=True, editable=False)),
                ("pupdate", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "Kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube.kategori",
                    ),
                ),
            ],
        ),
    ]
